### ISSUE TITLE
Process Map/Timeliner (enhancement)

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#35]
Future idea/request. Would it be possible to make process map/timeliner a tab? Say for example, you click the process map or timeliner tab. The process/timeliner tab opens and generates the graph. If there is a way to save this data, every time you open the tab thereafter, the graph would be presented and not have to be generated every time. If you don't like the idea, just close this.

**Comment by kevthehermit** [comment]
Output is now stored so you don't have to run the module every time, Will leave it in the same place for now. Will look at placing in a tab later. 

Timeline has a dot output as well, but i only ever seem to get a flat line, rather than a tree style structure, so i may drop this and just leave the table output in the plugin list.

**Comment by Beercow** [comment]
Works like a charm! Thank you for your time and effort. It is greatly appreciated :)

**Comment by kevthehermit** [comment]
:)
